### ISSUE TITLE
[DataCap Application] <The Second Life> - <3D printed>

### ISSUE THREAD

**Issue by AlterEgogo** [FilscanOfficial/filscan-backend#4]
### Data Owner Name

The Second Life

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

https://mp.weixin.qq.com/s/IMtL_m4sQAxqCmNWlw28Gw

### Social Media Handle

https://mp.weixin.qq.com/s/IMtL_m4sQAxqCmNWlw28Gw

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

450TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

1PiB

### On-chain address for first allocation

f1iuv4quvro3m2soa2qcte664enuprw3237ilsn2a

### Data Type of Application

Public, Open Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
The Second Life Universe Block is a digital hipster block with 3D printing and digital twins as the underlying technology, and a collection of 3D-printed real-life artefacts, 3D-printed coffee, and meta-universe experiences. Embrace the future, private ordering, self-realisation, and one-click construction of the second life of real human beings.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### Describe the data being stored onto Filecoin

```text
For each 3D printed model, we need to take high-precision photos of the 360-degree panorama. The production photos for one model are up to tens of thousands of photos, and we will model the model in 3D. We need to store these photos, models and other data
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We currently store our data on our own work computers, and on servers in the server room. In the case of data from the computers we will transfer it over the network, and in the case of data from the server we can do hard drive mailing
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
We have not previously stored on an IPFS network and the cost of storing on an IPFS network will make it much cheaper for us to do business.SP's information is something we are currently in contact with on an ongoing basis, and I will disclose it below in the request form.
```

### Please share a sample of the data

```text
You can check out the WeChat video number, the name of the account is "第二人生3D真人手办".
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

2 to 3 years

### In which geographies do you plan on making storage deals

Greater China, Africa, North America

### How will you be distributing your data to storage providers

HTTP or FTP server, IPFS

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03157883 - shenzhen
f02826815 - HK
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by FilscanOfficial** [comment]
@AlterEgogo 
I have reviewed your application and you need to provide additional KYB and KYC documents. You can send an email to filscanteam@outlook.com with your company's KYB information and SP's KYC information. Thank you.

**Comment by AlterEgogo** [comment]
Hello @FilscanOfficial , 
the email has been sent, please check it.

**Comment by FilscanOfficial** [comment]
@AlterEgogo 
I received your email, but I hope your information can be described in more detail to help me verify the SP information. Please add more information, thank you!

**Comment by AlterEgogo** [comment]
@FilscanOfficial 
Sorry, I have reorganised the information and re-sent the email, please check.

**Comment by AlterEgogo** [comment]
Hi,  @FilscanOfficial 
Node information will be added and I will send you proof of their address in the mail!
f02828269 - Shenzhen
f02826253 - Singapore
f02825282 - HK

**Comment by AlterEgogo** [comment]
The project data is being re-prepared, and we need to pause for a while. Therefore, I will temporarily close this issue. Once the data is ready and the project needs to continue, I will reopen it.

**Comment by filecoin-watchdog** [comment]
checker:manualTrigger

**Comment by FilscanOfficial** [comment]
@AlterEgogo  
This question: Is this project related to other projects/ecosystem stakeholders?
Your answer: Yes
Who are the stakeholders? Please add more answers, thank you!

**Comment by AlterEgogo** [comment]
Hello, @FilscanOfficial 
we are a 3D model generation and production team, and the stakeholders are all manufacturers in the physical industry.
If your question here is about projects related to filecoin, then we do not have such a type of partnership.
